# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mynd < Formula
  desc "Persistent memory mcp server for ai coding agents. injects project context at se"
  homepage "https://github.com/oxHive/mynd"
  url "https://github.com/oxHive/mynd/archive/refs/tags/v0.15.1.tar.gz"
  sha256 "45564f867d3161e6a8ae68d6c83f7367fac29a3ad9bf0e0d95a265d3ffffc0af"
  license "AGPL-3.0"

  on_macos do
    on_arm do
      url "https://github.com/oxHive/mynd/releases/download/v0.15.1/mynd-0.15.1-darwin-arm64.tar.gz"
      sha256 "e5683b102e6b503030a16d870684ac62450c7fd1899555e56730006e738d814f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxHive/mynd/releases/download/v0.15.1/mynd-0.15.1-linux-amd64.tar.gz"
      sha256 "ac8144ab9006755d5fc1151121ddc30e19e2011406d9fa7b0d7dd38a92bb163a"
    end

    on_arm do
      url "https://github.com/oxHive/mynd/releases/download/v0.15.1/mynd-0.15.1-linux-arm64.tar.gz"
      sha256 "0270d37cdd2d50e4a5ede1c6c0c8769c8572bd338f7f66e231cd5d571642210f"
    end
  end

  def install
    bin.install "mynd"
  end

  test do
    system "#{bin}/mynd", "--version"
  end
end
