# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Oxr < Formula
  desc "Semantic-version bump and git-tag orchestrator for manifest-less repos"
  homepage "https://github.com/oxHive/oxr"
  url "https://github.com/oxHive/oxr/archive/refs/tags/v0.1.0-rc.8.tar.gz"
  sha256 "8b843ecdeed3aaae33a3d48713766916ee9d62b61ca67d3a344130294deef317"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/oxHive/oxr/releases/download/v0.1.0-rc.8/oxr-0.1.0-rc.8-darwin-arm64.tar.gz"
      sha256 "52d9224d621f3d092a9769b3899cbce75c0bf4ed933439c7850707f2f6c82d69"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxHive/oxr/releases/download/v0.1.0-rc.8/oxr-0.1.0-rc.8-linux-amd64.tar.gz"
      sha256 "eba9819adbb7c620218305ab09ba6853f504d45825301fd303c97167ad12f147"
    end

    on_arm do
      url "https://github.com/oxHive/oxr/releases/download/v0.1.0-rc.8/oxr-0.1.0-rc.8-linux-arm64.tar.gz"
      sha256 "5e3f18156f39dd2fe8b1ca4b21e230042be316053b886cc881382aef4908d809"
    end
  end

  def install
    bin.install "oxr"
  end

  test do
    system "#{bin}/oxr", "--version"
  end
end
