# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Oxr < Formula
  desc "Semantic-version bump and git-tag orchestrator for manifest-less repos"
  homepage "https://github.com/oxHive/oxr"
  url "https://github.com/oxHive/oxr/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "3e6c509c14cec219dff78de4a4fc6f6ad182708ae41d855980caa0337a667faa"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/oxHive/oxr/releases/download/v0.2.0/oxr-0.2.0-darwin-arm64.tar.gz"
      sha256 "a8a2e7d89473cfabd5154051e17aa8575294774229ba2a1ab743493fddacb485"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxHive/oxr/releases/download/v0.2.0/oxr-0.2.0-linux-amd64.tar.gz"
      sha256 "ab543a5b26185e7c320cbcc681fe19d6151ad23f9f00dd41456009db6a184d10"
    end

    on_arm do
      url "https://github.com/oxHive/oxr/releases/download/v0.2.0/oxr-0.2.0-linux-arm64.tar.gz"
      sha256 "6b17b05e9eaa3fc93f47b999f56aaaa21f4e3e1336c6f5db04f376edbbbace44"
    end
  end

  def install
    bin.install "oxr"
  end

  test do
    system "#{bin}/oxr", "--version"
  end
end
