# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Oxr < Formula
  desc "Semantic-version bump and git-tag orchestrator for manifest-less repos"
  homepage "https://github.com/oxHive/oxr"
  url "https://github.com/oxHive/oxr/archive/refs/tags/v0.1.0-rc.7.tar.gz"
  sha256 "5405a943214ae7dbfcf7ca0b6c4d4643431871f9312c14ab48f2d7598588d35d"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/oxHive/oxr/releases/download/v0.1.0-rc.7/oxr-0.1.0-rc.7-darwin-arm64.tar.gz"
      sha256 "51136200160d26767a65fec8a325506a11d71f3100381bcb6e5464496abcc5f9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxHive/oxr/releases/download/v0.1.0-rc.7/oxr-0.1.0-rc.7-linux-amd64.tar.gz"
      sha256 "8ed3700251d1106e8d5ed54d9056f9eb3ed69093e134bd5ed7ebd569e0680627"
    end

    on_arm do
      url "https://github.com/oxHive/oxr/releases/download/v0.1.0-rc.7/oxr-0.1.0-rc.7-linux-arm64.tar.gz"
      sha256 "67ba09883c99c9f68c170272123e76413e8240b4f98328fdafde3c45e78cfa48"
    end
  end

  def install
    bin.install "oxr"
  end

  test do
    system "#{bin}/oxr", "--version"
  end
end
