# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Wardn < Formula
  desc "Is a small, self-hostable, open source service that gives mynd organizatio"
  homepage "https://github.com/oxHive/wardn"
  url "https://github.com/oxHive/wardn/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "3aebbdf3b90746a7042a46f3021bdc915020409462e6c46dec1d30f5f437b25b"
  license "AGPL-3.0"

  on_macos do
    on_arm do
      url "https://github.com/oxHive/wardn/releases/download/v0.1.0/wardn-0.1.0-darwin-arm64.tar.gz"
      sha256 "07bb39f09dcb0797d7e2ac65824102ceca26b4df7ea18341fc5f865c0948efdc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxHive/wardn/releases/download/v0.1.0/wardn-0.1.0-linux-amd64.tar.gz"
      sha256 "dd61ef1dbe674662200fb17eb4d3a9189b8974ef9b8a8369757af046601cb59e"
    end

    on_arm do
      url "https://github.com/oxHive/wardn/releases/download/v0.1.0/wardn-0.1.0-linux-arm64.tar.gz"
      sha256 "398cf28ebaaf584718325fb70308bfd835aade27d9808dc951d277e4c9e73c49"
    end
  end

  def install
    bin.install "wardn"
  end

  test do
    system "#{bin}/wardn", "--version"
  end
end
